FROM rabbitmq:3.12.4

# Enable plugin
COPY ./docker/rabbitMq/rabbitmq_delayed_message_exchange-3.12.0.ez /plugins/rabbitmq_delayed_message_exchange-3.12.0.ez
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange

# Run
CMD ["rabbitmq-server"]
